import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { Heart, ShieldCheck, Sparkles, Sprout } from 'lucide-react';

const About = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />

      <main className="flex-grow max-w-4xl mx-auto px-4 py-12 w-full space-y-12">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-extrabold font-sans">About PlatePulse</h1>
          <p className="text-sm text-zinc-500 font-bold uppercase tracking-wider text-amber-500">Connecting Surplus Food with Those Who Need It Most</p>
        </div>

        <div className="glass-panel p-8 bg-white/60 space-y-6">
          <h3 className="font-extrabold text-xl">Our Vision</h3>
          <p className="text-zinc-600 dark:text-zinc-400 text-sm leading-relaxed font-medium">
            PlatePulse was established to tackle two major modern challenges: the severe urban food wastes generated by high-end hotels, wedding caterers, and residences, and the persistent issue of community hunger. By providing a modern, audited verification dashboard, we enable businesses and people to share food safety margins and deliver meals securely to local shelters.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="glass-card p-6 bg-white/50 space-y-3">
            <div className="p-3 bg-amber-500/10 rounded-xl text-amber-500 w-fit">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <h4 className="font-bold text-lg">Fully Verified KYC</h4>
            <p className="text-xs text-zinc-500 leading-relaxed font-semibold">
              All NGOs on our platform undergo Darpan ID auditing and live 1-to-1 video verifications, ensuring donations are received and distributed by legitimate parties.
            </p>
          </div>

          <div className="glass-card p-6 bg-white/50 space-y-3">
            <div className="p-3 bg-emerald-500/10 rounded-xl text-emerald-600 w-fit">
              <Sprout className="w-6 h-6" />
            </div>
            <h4 className="font-bold text-lg">Carbon Reduction Tracking</h4>
            <p className="text-xs text-zinc-500 leading-relaxed font-semibold">
              Mitigating food waste reduces greenhouse gas emissions. Our analytics report and ledger compile exact weights and impact calculations of saved meals.
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default About;
